apply plugin: 'com.android.library'
apply from: '../common/VERSIONS.gradle'

android {
    compileSdkVersion project.ext.getCompileSdkVersion()

    defaultConfig {
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        minSdkVersion project.ext.getMinSdkVersion()
        targetSdkVersion project.ext.getTargetSdkVersion()
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        //unitTests.includeAndroidResources = true
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation testLibs.junit
    testImplementation testLibs.robolectric
    implementation libs.slf4j
    implementation project(':CordovaLib')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(path: ':common')
}
